server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/自己数据库?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    username: # 数据库用户名
    password: # 数据库密码
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  servlet:
    multipart:
      max-request-size: 100MB  # 最大请求大小
      max-file-size: 300MB   # 最大文件大小
# 阿里配置3 -- 上下密钥为同一个
al:
  oss: #存储
    endpoint:  # 域
    accessKeyId: # 秘钥
    accessKeySecret: # 秘钥
    bucketName: # 桶名
    url: # 访问地址
  vod: # 视频
    regionId: # 区域
    accessKeyId:  # 秘钥
    accessKeySecret: # 秘钥